name: auto-build
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/update*
    paths:
      # build対象となるsrcファイルに差分がある場合
      - "src/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # secrets.GITHUB_TOKENでcommit&pushしても次のワークフローを起動しないためGitHub Appから一時tokenを発行する
      # see https://github.com/marketplace/actions/github-app-token
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ steps.generate_token.outputs.token }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - name: Load version
        uses: xom9ikk/dotenv@v2
        with:
          path: src
      - name: build diagram
        env:
          GITHUB_PACKAGE_USERNAME: Seo-4d696b75
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p src/diagram/build
          bundle exec ruby src/script/prebuild_diagram.rb
          cd src/diagram
          ./gradlew run --args="build/station.json build/diagram.json"
          ./gradlew run --args="build/station.extra.json build/diagram.extra.json"
      - name: build data
        run: |
          bundle exec ruby src/script/build.rb 
          bundle exec ruby src/script/build.rb -e
      - name: Check Diff
        id: check_diff
        run: |
          git add -N .
          main=$(git diff --name-only -- out/main/ | wc -l)
          extra=$(git diff --name-only -- out/extra/ | wc -l)
          echo "detected file changes main: $main, extra: $extra"
          echo "main=$main" >> $GITHUB_OUTPUT
          echo "extra=$extra" >> $GITHUB_OUTPUT
      - name: update summary (main)
        if: ${{ steps.check_diff.outputs.main }} > 0
        run: |
          ./src/zip.sh main
          bundle exec ruby src/script/release.rb \
            -s out/main/json.zip \
            -d latest_info.json \
            -v ${{ env.VERSION }}
      - name: update summary (extra)
        if: ${{ steps.check_diff.outputs.extra }} > 0
        run: |
          ./src/zip.sh extra
          bundle exec ruby src/script/release.rb \
            -s out/extra/json.zip \
            -d latest_info.extra.json \
            -v ${{ env.VERSION }}
      - name: Commit and Push
        if: ${{ steps.check_diff.outputs.main }} + ${{ steps.check_diff.outputs.extra }} > 0
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          git add ./src ./out
          git commit -m "[build] version ${{ env.VERSION }}"
          git add ./latest*
          git commit -m "[update] version info ${{ env.VERSION }}"
          git push origin ${{ github.ref_name }}
