name: auto-build
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/update*
    paths:
      # build対象となるsrcファイルに差分がある場合
      - "src/**"
      - ".github/workflows/build.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # secrets.GITHUB_TOKENでcommit&pushしても次のワークフローを起動しないためGitHub Appから一時tokenを発行する
      # see https://github.com/marketplace/actions/create-github-app-token
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}
          token: ${{ steps.generate_token.outputs.token }}
      - name: setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .tool-versions
          cache: "npm"
      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      - name: setup node modules
        run: npm ci
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - name: Load version
        uses: ./.github/actions/load-dotenv
        with:
          path: src
      - name: build diagram
        env:
          GITHUB_PACKAGE_USERNAME: Seo-4d696b75
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p src/diagram/build
          npm run prebuild-diagram
          cd src/diagram
          ./gradlew run --args="build/station.json build/diagram.json"
          ./gradlew run --args="build/station.extra.json build/diagram.extra.json"
      - name: build data
        run: npm run build
      - name: Check Diff
        id: check_diff
        run: |
          git add -N .
          main=$(git diff --name-only -- out/main/ | wc -l)
          extra=$(git diff --name-only -- out/extra/ | wc -l)
          echo "detected file changes main: $main, extra: $extra"
          echo "main=$([ "$main" -gt 0 ] && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
          echo "extra=$([ "$extra" -gt 0 ] && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
      - name: update summary (main)
        if: steps.check_diff.outputs.main == 'true'
        run: |
          ./src/zip.sh main
          npm run bump-version-main
      - name: update summary (extra)
        if: steps.check_diff.outputs.extra == 'true'
        run: |
          ./src/zip.sh extra
          npm run bump-version-extra
      - name: Configure GPG
        if: steps.check_diff.outputs.main == 'true' || steps.check_diff.outputs.extra == 'true'
        uses: ./.github/actions/configure-gpg
        with:
          private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          key-id: ${{ secrets.GPG_KEY_ID }}
          user-email: ${{ secrets.GPG_USER_EMAIL }}
          user-name: ${{ secrets.GPG_USER_NAME }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          key-grip: ${{ secrets.GPG_KEY_GRIP }}
      - name: Commit and Push
        if: steps.check_diff.outputs.main == 'true' || steps.check_diff.outputs.extra == 'true'
        run: |
          git add ./src ./out
          git commit -m "feat: build v${{ env.VERSION }}"
          git add ./latest*
          git commit -m "feat: update version info v${{ env.VERSION }}"
          git push origin ${{ github.ref_name }}
