name: auto-build
on:
  push:
    branches:
      - develop
      - feature/update*
    paths: 
      # build対象となるsrcファイルに差分がある場合
      - 'src/check/*'
      - 'src/line/*'
      - 'src/polyline/*'
      - 'src/*.csv'
      - 'src/.env'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Load version
        uses: xom9ikk/dotenv@v2
        with:
          path: src
      - name: build diagram
        env:
          GITHUB_PACKAGE_USERNAME: Seo-4d696b75
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p src/diagram/build
          bundle exec ruby src/script/prebuild_diagram.rb
          cd src/diagram
          ./gradlew run --args="build/station.json build/diagram.json"
          ./gradlew run --args="build/station.extra.json build/diagram.extra.json"
      - name: build data
        run: |
          bundle exec ruby src/script/pack.rb \
            -d out/main \
            -v ${{ env.VERSION }}
          bundle exec ruby src/script/pack.rb \
            -e \
            -d out/extra \
            -v ${{ env.VERSION }}
      - name: zip data
        run: |
          ./src/zip.sh main
          ./src/zip.sh extra
      - name: Check Diff
        id: check_diff
        run: |
          git add -N .
          echo "main=$(git diff --name-only -- out/main/ | wc -l)" >> $GITHUB_OUTPUT
          echo "extra=$(git diff --name-only -- out/extra/ | wc -l)" >> $GITHUB_OUTPUT
      - name: Update Info (main)
        if: ${{ steps.check_diff.outputs.main }} > 0
        run: |
          bundle exec ruby src/script/release.rb \
            -s out/main/data.json \
            -d latest_info.json \
            -v ${{ env.VERSION }}
      - name: Update Info (extra)
        if: ${{ steps.check_diff.outputs.extra }} > 0
        run: |
          bundle exec ruby src/script/release.rb \
            -s out/extra/data.json \
            -d latest_info.extra.json \
            -v ${{ env.VERSION }}
      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          git add ./src ./out
          git commit -m "[build] version ${{ env.VERSION }}"
          git add ./latest*
          git commit -m "[update] version info ${{ env.VERSION }}"
          git push origin ${{ github.ref_name }}
