name: auto-build
on:
  pull_request:
    branches:
      - main
    paths: 
      - 'src/check/*'
      - 'src/line/*'
      - 'src/polyline/*'
      - 'src/*.csv'
    types: 
      - closed

permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # PRがmainにマージされたとき
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Load version
        uses: xom9ikk/dotenv@v2
        with:
          path: src
      - name: Check Build Dir
        run: |
          mkdir -p build
          mkdir -p build/polyline
      - name: Run Checks
        run: |
          ruby src/script/check.rb -d out/main
          ruby src/script/check.rb -e -d out/extra
      - name: Build Polyline
        run: ruby src/script/polyline.rb
      - name: Build Voronoi
        env:
          GITHUB_PACKAGE_USERNAME: Seo-4d696b75
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src/diagram
          ./gradlew run --args="../../build/station.json ../../build/diagram.json"
          ./gradlew run --args="../../build/station.extra.json ../../build/diagram.extra.json"
      - name: Pack Data
        run: |
          ruby src/script/pack.rb -d out/main -v ${{ env.VERSION }}
          ruby src/script/pack.rb -e -d out/extra -v ${{ env.VERSION }}
      - name: Check Diff
        id: check_diff
        runs: |
          git add -N .
          echo "main=$(git diff --name-only -- out/main/ | wc -l)" >> $GITHUB_OUTPUT
          echo "extra=$(git diff --name-only -- out/extra/ | wc -l)" >> $GITHUB_OUTPUT
      - name: Update Info (main)
        if: ${{ steps.check_diff.outputs.main }} > 0
        run: ruby src/script/release.rb -s out/main/data.json -d latest_info.json -v ${{ env.VERSION }}
      - name: Update Info (extra)
        if: ${{ steps.check_diff.outputs.extra }} > 0
        run: ruby src/script/release.rb -s out/extra/data.json -d latest_info.extra.json -v ${{ env.VERSION }}
      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          git add ./src ./out
          git commit -m "[build] version ${{ env.VERSION }}"
          git add ./latest*
          git commit -m "[update] version info ${{ env.VERSION }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          branch-suffix: timestamp
          base: main
          title: "[Build] version ${{ env.VERSION }}"
          body: "auto build"