name: check-src
on:
  pull_request:
    branches:
      - main
    paths: 
      - 'src/check/*'
      - 'src/line/*'
      - 'src/polyline/*'
      - 'src/*.csv'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
      - name: Run Test (main)
        run: ruby src/script/check.rb
      - name: Run Test (extra)
        run: ruby src/script/check.rb -e
