name: check-update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1,3,5" # JSTで毎週月・水・金曜18:00に実行
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: "npm"
      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      - name: setup node modules
        run: npm ci
      - name: run script
        run: npm run check-update
