name: download
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 1 * *" # JSTで毎月１日18:00に実行（低頻度）
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"
      - name: setup node modules
        run: npm install
      - name: download
        run: |
          mkdir -p src/ekimemo/station src/ekimemo/line
          rm -f src/ekimemo/station/* src/ekimemo/line/*
          npm run download
      - name: cache downloaded data
        if: success()
        uses: actions/cache/save@v3
        with:
          path: |
            src/ekimemo/station
            src/ekimemo/line
          key: ekimemo-data-latest
