name: ekimemo
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *" # JSTで毎月１日21:00に実行（ダウンロード完了から3時間後）
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: restore cached data
        uses: actions/cache/restore@v3
        with:
          path: |
            src/ekimemo/station
            src/ekimemo/line
          key: ekimemo-data-latest
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"
      - name: setup node modules
        run: npm install
      - name: run test
        run: npm run test-ekimemo
