name: auto-release
on:
  pull_request:
    branches:
      - main
    types: 
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    # PRがmainにマージされたとき
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Load version
        uses: xom9ikk/dotenv@v2
        with:
          path: src
      - name: Add Tag
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          git tag -a "v${{ env.VERSION }}" -m "駅情報更新 ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "駅情報更新 ${{ env.VERSION }}"
          draft: true
          prerelease: false