name: auto-release
on:
  pull_request:
    branches:
      - main
    paths:
      - 'out/**/*'
    types: 
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # PRがmainにマージされたとき
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: 'main'
      - name: Load version
        uses: ./.github/actions/load-dotenv
        with:
          path: src
      - name: Add Tag
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          git tag -a "v${{ env.VERSION }}" -m "駅情報更新 ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --repo "${{ github.repository }}" \
            --title "駅情報更新 ${{ env.VERSION }}" \
            --draft
