name: auto-release
on:
  push:
    tags: 
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Set version value
        id: version
        run: |
          VALUE=$(echo ${{ github.ref }} | sed -e "s/^.*v\([0-9]*\)/\1/")
          echo "::set-output name=value::${VALUE}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: version ${{ steps.version.outputs.value }}
          draft: true
          prerelease: false
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: update info
        run: |
          ruby src/script/release.rb ${{ steps.version.outputs.value }}
      - name: commit manifests and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "s.kaoru509@gmail.com"
          git config --global user.name "Seo-4d696b75"
          git add .
          git commit -m '[update] latest-info version:${{steps.version.outputs.value}}'
          git push origin master