name: auto-release
on:
  pull_request:
    branches:
      - main
    paths:
      - 'out/**/*'
    types: 
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # PRがmainにマージされたとき
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Load version
        uses: ./.github/actions/load-dotenv
        with:
          path: src
      - name: Configure GPG
        uses: ./.github/actions/configure-gpg
        with:
          private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          key-id: ${{ secrets.GPG_KEY_ID }}
          user-email: ${{ secrets.GPG_USER_EMAIL }}
          user-name: ${{ secrets.GPG_USER_NAME }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          key-grip: ${{ secrets.GPG_KEY_GRIP }}
      - name: Add Tag
        run: |
          git tag -s "v${{ env.VERSION }}" -m "駅情報更新 ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --repo "${{ github.repository }}" \
            --title "駅情報更新 ${{ env.VERSION }}" \
            --draft
