name: format-test
on:
  pull_request:
    branches:
      - main
    paths: 
      - 'out/**/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
      - name: setup node modules
        run: npm install
      - name: run test (main)
        run: npm run test-format-main
      - name: run text (extra)
        run: npm run test-format-extra
