name: format-test
on:
  push:
    paths: 
      - 'out/main/**'
      - 'out/extra/**'
      - 'src/ts/**'
      - '.github/workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
          fetch-depth: 0
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
      - name: setup node modules
        run: npm install
      - name: run test (main)
        run: npm run test-format-main
      - name: run text (extra)
        run: npm run test-format-extra
