name: test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'out/**/*'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm' 
      - name: setup node modules
        run: npm install
      - name: run test (main)
        run: npm run test-format-main
      - name: run text (extra)
        run: npm run test-format-extra
  consistency:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
        with:
          ref: ${{github.head_ref}}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: fetch data from 'main' branch
        run: |
          mkdir artifact
          curl https://raw.githubusercontent.com/Seo-4d696b75/station_database/main/out/main/data.json -o artifact/main.json
          curl https://raw.githubusercontent.com/Seo-4d696b75/station_database/main/out/extra/data.json -o artifact/extra.json
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
      - name: compare data
        run: |
          bundle exec ruby src/script/test_update.rb \
            -o artifact/main.json \
            -n out/main/data.json \
            -l diff.main.md \
            -m "detected changes in 'main' dataset"
          bundle exec ruby src/script/test_update.rb \
            -o artifact/extra.json \
            -n out/extra/data.json \
            -l diff.extra.md \
            -m "detected changes in 'extra' dataset"
          bundle exec ruby src/script/test_subset.rb \
            -m out/main/data.json \
            -e out/extra/data.json
      - name: check comment
        run: |
          cat artifact/diff.main.md
          cat artifact/diff.extra.md
          touch .github/workflows/diff.md
          cat .github/workflows/diff.main.md >> .github/workflows/diff.md
          cat .github/workflows/diff.extra.md >> .github/workflows/diff.md
      - name: comment on PR
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: diff.md # .github/workflows/ ディレクトリ以下固定
      - uses: actions/upload-artifact@v2
        with:
          name: diff
          path: artifact/*.md