name: format-test
on:
  push:
    branches:
      - extra-update
      - extra
    path: 'out/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'extra-update'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
      - name: run test
        run: |
          gem install minitest
          ruby src/script/test_format.rb
