name: test
on:
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"
      - name: setup node modules
        run: npm install
      - name: run test (main format)
        run: npm run test-format-main
      - name: run test (extra format)
        run: npm run test-format-extra
      - name: run test (subset)
        run: npm run test-subset
  fetch-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.base_ref}}
      - name: fetch data
        run: |
          mkdir artifact
          cp out/main/json.zip artifact/main.zip
          cp out/extra/json.zip artifact/extra.zip
          cp src/.env artifact/.env
      - uses: actions/upload-artifact@v4
        with:
          name: base-data
          path: artifact
          # .env ファイルもアップロードする
          include-hidden-files: true
  consistency:
    runs-on: ubuntu-latest
    needs: fetch-base
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"
      - name: setup node modules
        run: npm install
      - name: download base data
        uses: actions/download-artifact@v4
        with:
          name: base-data
          path: artifact
      - name: test version
        run: npm run test-version
      - name: unzip base data
        run: |
          unzip -q artifact/main.zip -d artifact
          mv artifact/json artifact/main
          unzip -q artifact/extra.zip -d artifact
          mv artifact/json artifact/extra
      - name: compare data
        # TODO idの破壊的変更によりテストが落ちるため一時的に無効化する
        if: false
        run: |
          npm run test-update-main
          npm run test-update-extra
          cat artifact/diff.extra.md >> artifact/diff.md
          rm artifact/diff.extra.md
      - name: comment on PR
        if: false
        uses: thollander/actions-comment-pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filePath: artifact/diff.md
          comment_tag: diff
      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: diff
          path: artifact/*.md
