name: test
on:
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"
      - name: setup node modules
        run: npm install
      - name: run test (main)
        run: npm run test-format-main
      - name: run text (extra)
        run: npm run test-format-extra
  fetch-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.base_ref}}
      - name: fetch data
        run: |
          mkdir artifact
          cp out/main/json.zip artifact/main.zip
          cp out/extra/json.zip artifact/extra.zip
          cp src/.env artifact/.env
      - uses: actions/upload-artifact@v4
        with:
          name: base-data
          path: artifact
  consistency:
    runs-on: ubuntu-latest
    needs: fetch-base
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: download base data
        uses: actions/download-artifact@v4
        with:
          name: base-data
          path: artifact
      - name: unzip base data
        run: |
          unzip -q artifact/main.zip -d artifact
          mv artifact/json artifact/main
          unzip -q artifact/extra.zip -d artifact
          mv artifact/json artifact/extra
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
      - name: check version
        run: bundle exec ruby src/script/test_version.rb
      - name: check subset
        run: bundle exec ruby src/script/test_subset.rb
      - name: compare data
        run: |
          bundle exec ruby src/script/test_update.rb 
          bundle exec ruby src/script/test_update.rb -e
          cat artifact/diff.extra.md >> artifact/diff.md
          rm artifact/diff.extra.md
      - name: comment on PR
        uses: thollander/actions-comment-pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filePath: artifact/diff.md
          comment_tag: diff
      - uses: actions/upload-artifact@v4
        with:
          name: diff
          path: artifact/*.md
