name: ConsistencyTest
on:
  push:
    branches:
      - action-test
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: install minitest
        run: |
          gem install minitest
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
      - name: run test
        run: |
          cd src
          ruby ./script/test.rb
